### ISSUE TITLE
Scrollbar colour in tree view

### ISSUE THREAD

**Issue by niccolomineo** [dmitmel/atom-intellij-darcula-syntax#1]
Hi, this syntax scheme is amazing! Been using it since I switched to Atom.

I noticed this is the scrollbar's appearance in the tree view:

![schermata 2017-09-20 alle 00 42 40](https://user-images.githubusercontent.com/5409469/30618887-c0d05294-9d9c-11e7-8d3c-b9ece080c4ca.png)

Would it be possible to have it match the colour and behaviour of the main editor scrollbars (dark colour, clear and larger hover)?

Thank you and keep up the great work,
N

**Comment by dmitmel** [comment]
I've moved from Atom to Visual Studio Code, so this theme is no longer actively supported by me. Recent Atom updates could change appearance of the theme.

[Scrollbar styling](https://discuss.atom.io/t/change-the-color-and-width-of-editors-sidebar/18545/3) is supported in Atom, so I'll try to fix this issue.

**Comment by niccolomineo** [comment]
Thank you man, looking forward to it.

**Comment by dmitmel** [comment]
I think that this is an issue of **UI theme**, not **syntax theme**. **Syntax themes** add styles to the editor, not to the tree view. You should add an issue to the repository of your **UI theme**.

**Comment by niccolomineo** [comment]
Ok, thanks, although the UI theme is One Dark...

![schermata 2017-09-22 alle 21 03 28](https://user-images.githubusercontent.com/5409469/30760231-a267503e-9fd9-11e7-9acf-363b39901f5b.png)

**Comment by dmitmel** [comment]
https://github.com/atom/one-dark-ui/issues

**Comment by dmitmel** [comment]
Try this:
1. Open **Atom > Stylesheet...**
2. Insert the following code:
   ```less
   .tree-view::-webkit-scrollbar {
       background-color: #262626;
       &-track {}

       &-thumb {
           background-color: #404040;
           &:window-inactive {
               background-color: rgb(116, 115, 105);
           }
       }

       &-corner {
           background-color: #262626;
       }
   }
   ```
